# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#sql script

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

#steps:
#- script: echo Freshness report starting!
#  displayName: 'Freshness report starting!'
#- script: git clone https://github.com/diberry/freshness-public
#  displayName: 'git freshness-public!'
#  workingDirectory: $(Agent.BuildDirectory)
#- script: ls ./freshness-public -l
#  displayName: 'list contents of ./freshness-public'
#  workingDirectory: $(Agent.BuildDirectory)
#- script: git clone https://github.com/MicrosoftDocs/azure-docs
#  displayName: 'git azure-docs'
#  workingDirectory: $(Agent.BuildDirectory)
#- script: ls
#  displayName: 'list contents of ./ (root directory)'
#  workingDirectory: $(Agent.BuildDirectory)  
#- powershell:  ./freshness-public/getfreshness.ps1 ./azure-docs/articles/cognitive-services/
#  workingDirectory:  $(Agent.BuildDirectory)
#  displayName:  'get freshness report with powershell script'
#  failOnStderr: false
#  errorActionPreference:  silentlyContinue
#  ignoreLASTEXITCODE:  true
#- script: ls -l
#  displayName: 'list contents of ./ (root directory)'
#  workingDirectory: $(Agent.BuildDirectory)
#- script: zip -r freshness.zip freshness.csv 
#  displayName: 'zip up file into freshness.zip'
#  workingDirectory: $(Agent.BuildDirectory) 
#- script: ls -l
#  displayName: 'check if zip file was created'
#  workingDirectory: $(Agent.BuildDirectory)  
#- task: PublishPipelineArtifact@0
#  displayName: 'Publish artifact'
#  inputs:
#    artifactName: 'freshness.zip' 
#    targetPath: $(Build.ArtifactStagingDirectory)
#- script: echo Freshness report done!
#  displayName: 'Freshness report done!'

variables:
  AzureSubscription: '65a1016d-0f67-45d2-b838-b8f373d6d52e'
  ServerName: 'diberry-personal.database.windows.net'
  DatabaseName: 'diberry-personal'
  AdminUser: 'Sql'
  AdminPassword: 'Redrum1!'
  SQLFile: 'insert-into-sql.sql'

steps:
- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\SetAzureFirewallRule.ps1'
    ScriptArguments: '$(ServerName)'
    azurePowerShellVersion: LatestVersion

- task: CmdLine@1
  displayName: Run Sqlcmd
  inputs:
    filename: Sqlcmd
    arguments: '-S $(ServerName) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'

- task: AzurePowerShell@2
  displayName: Azure PowerShell script: FilePath
  inputs:
    azureSubscription: '$(AzureSubscription)'
    ScriptPath: '$(Build.SourcesDirectory)\scripts\RemoveAzureFirewallRule.ps1'
    ScriptArguments: '$(ServerName)'
    azurePowerShellVersion: LatestVersion