# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Freshness report starting!
  displayName: 'Freshness report starting!'
- script: git clone https://github.com/diberry/freshness-public
  displayName: 'git freshness-public!'
  workingDirectory: $(Agent.BuildDirectory)
- script: git clone https://github.com/MicrosoftDocs/azure-docs
  displayName: 'git azure-docs'
  workingDirectory: $(Agent.BuildDirectory)
- script: ls
  displayName: 'list contents'
  workingDirectory: $(Agent.BuildDirectory)  
